export const listItems = [
    { id: 1, label: 'Vampiro'           , total: 150.00, image: "/img/drink_menu.png" },
    { id: 2, label: 'Paloma'            , total: 150.00, image: "/img/drink.png" },
    { id: 3, label: 'Clamato'           , total: 150.00, image: "/img/drink.png" },
    { id: 4, label: 'Michelada'         , total: 150.00, image: "/img/drink.png" },
    { id: 4, label: 'Whisky'            , total: 200.00, image: "/img/drink.png" },
    { id: 4, label: 'Mojito Tradicional', total: 150.00, image: "/img/drink.png" },
    { id: 4, label: 'Mojito Fresa'      , total: 150.00, image: "/img/drink.png" },
    { id: 4, label: 'Piña Colada'       , total: 150.00, image: "/img/drink.png" },
    { id: 4, label: 'Cerveza'           , total: 35.00, image: "/img/drink.png" },
    { id: 4, label: 'Margarita Mango'   , total: 150.00, image: "/img/drink.png" },
    { id: 4, label: 'Margarita Fresa'   , total: 150.00, image: "/img/drink.png" },
    { id: 4, label: 'Margarita Fresa ch'   , total: 65.00, image: "/img/drink.png" },
    { id: 4, label: 'Fucker'            , total: 200.00, image: "/img/drink.png" },
    { id: 4, label: 'Perla Negra'       , total: 200.00, image: "/img/drink.png" },
    { id: 1, label: 'Burritos'           , total: 125.00, image: "/img/food.png" },
    { id: 2, label: 'Hot Dog'            , total: 100.00, image: "/img/food_menu.png" },
    { id: 3, label: 'Papas a la Francesa', total: 30.00, image: "/img/food.png" },
    { id: 4, label: 'Tosticeviche'       , total: 120.00, image: "/img/food.png" },
    { id: 4, label: 'Tostada de ceviche' , total: 50.00, image: "/img/food.png" },
];